language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../Sort_things2
  - make -j
  - cd ./bin/
  - ./test_sorts
  - ./sample_sorts
  - git add ./output.csv
  - git commit -m "look"
  - git push origin HEAD
notifications:
  email: false
